import logging
import json
import time
import uuid
from contextvars import ContextVar

# Prometheus is optional for local smoke tests
try:
    from prometheus_client import Counter, Histogram, Gauge
    _HAS_PROM = True
except Exception:
    _HAS_PROM = False

logger = logging.getLogger("agentic_rag")

# Metrics (no-op fallbacks when prometheus_client isn't installed)
if _HAS_PROM:
    REQUEST_COUNTER = Counter("agentic_requests_total", "Total queries received")
    REQUEST_DURATION = Histogram("agentic_request_duration_seconds", "HTTP request duration seconds", ["method", "path", "status"])
    RETRIEVAL_LATENCY = Histogram("retrieval_latency_seconds", "Retrieval latency seconds")
    LLM_LATENCY = Histogram("llm_latency_seconds", "LLM call latency seconds")
    RERANKER_LATENCY = Histogram("reranker_latency_seconds", "Reranker latency seconds")
    AGENT_LATENCY = Histogram("agent_latency_seconds", "Agent latency seconds", ["agent"])
    CACHE_HITS = Counter("cache_hits_total", "Cache hit count")
    CACHE_MISSES = Counter("cache_misses_total", "Cache miss count")
    TOKEN_USAGE = Counter("llm_tokens_generated_total", "Approximate tokens generated by LLMs")
    TOOL_USAGE = Counter("tool_usage_total", "Tool executions", ["tool", "status"])
    VALIDATION_FAILURES = Counter("validation_failures_total", "Validation failures", ["kind"])
    HALLUCINATION_DETECTIONS = Counter("hallucination_detections_total", "Hallucination detections", ["severity"])
    COST_ESTIMATE = Counter("llm_cost_estimate_usd_total", "Estimated LLM cost in USD")
    ERROR_COUNTER = Counter("agentic_errors_total", "Total handled errors", ["component", "kind"])
else:
    class _Noop:
        def observe(self, *a, **k):
            pass

        def inc(self, *a, **k):
            pass

    REQUEST_COUNTER = _Noop()
    REQUEST_DURATION = _Noop()
    RETRIEVAL_LATENCY = _Noop()
    LLM_LATENCY = _Noop()
    RERANKER_LATENCY = _Noop()
    AGENT_LATENCY = _Noop()
    CACHE_HITS = _Noop()
    CACHE_MISSES = _Noop()
    TOKEN_USAGE = _Noop()
    TOOL_USAGE = _Noop()
    VALIDATION_FAILURES = _Noop()
    HALLUCINATION_DETECTIONS = _Noop()
    COST_ESTIMATE = _Noop()
    ERROR_COUNTER = _Noop()


def record_reranker_latency(seconds: float):
    try:
        RERANKER_LATENCY.observe(seconds)
    except Exception:
        pass


def record_agent_latency(agent: str, seconds: float):
    try:
        AGENT_LATENCY.labels(agent=agent).observe(seconds)
    except Exception:
        pass


TRACE_ID: ContextVar[str] = ContextVar("trace_id", default="")


_ALLOWED_RETRIEVAL_EVENTS = {
    "retrieval.enter",
    "retrieval.start",
    "retrieval.before_chroma",
    "retrieval.after_chroma",
    "retrieval.before_rerank",
    "retrieval.complete",
    "retrieval.completed",
    "retrieval.exception",
    "retrieval.cancelled",
    "retrieval.bm25.error",
    "retrieval.bm25.timeout",
    "retrieval.sparse.error",
}


def record_retrieval_latency(seconds: float):
    try:
        RETRIEVAL_LATENCY.observe(seconds)
    except Exception:
        pass


def record_llm_latency(seconds: float):
    try:
        LLM_LATENCY.observe(seconds)
    except Exception:
        pass


def record_tool_usage(tool: str, success: bool = True):
    try:
        TOOL_USAGE.labels(tool=tool, status="success" if success else "failure").inc()
    except Exception:
        pass


def record_validation_failure(kind: str):
    try:
        VALIDATION_FAILURES.labels(kind=kind).inc()
    except Exception:
        pass


def record_hallucination_detection(severity: str = "medium"):
    try:
        HALLUCINATION_DETECTIONS.labels(severity=severity).inc()
    except Exception:
        pass


def record_cost_estimate(usd: float):
    try:
        COST_ESTIMATE.inc(max(0.0, float(usd)))
    except Exception:
        pass


def inc_request():
    try:
        REQUEST_COUNTER.inc()
    except Exception:
        pass


def observe_request(method: str, path: str, status: int, duration: float):
    try:
        REQUEST_DURATION.labels(method=method, path=path, status=str(status)).observe(duration)
    except Exception:
        pass


def inc_error(component: str, kind: str = "error"):
    try:
        ERROR_COUNTER.labels(component=component, kind=kind).inc()
    except Exception:
        pass


def new_trace_id() -> str:
    return uuid.uuid4().hex


def set_trace_id(trace_id: str):
    TRACE_ID.set(trace_id)


def get_trace_id() -> str:
    return TRACE_ID.get()


def log_event(event: str, **fields):
    if event.startswith("retrieval.") and event not in _ALLOWED_RETRIEVAL_EVENTS:
        return
    payload = {
        "event": event,
        "trace_id": fields.pop("trace_id", get_trace_id()),
        "timestamp": time.time(),
        **fields,
    }
    try:
        logger.info(json.dumps(payload, default=str))
    except Exception:
        logger.info("%s %s", event, payload)


def cache_hit():
    try:
        CACHE_HITS.inc()
    except Exception:
        pass


def cache_miss():
    try:
        CACHE_MISSES.inc()
    except Exception:
        pass


def record_token_usage(count: int = 1):
    try:
        TOKEN_USAGE.inc(count)
    except Exception:
        pass


_OTEL_INITIALIZED = False


def init_opentelemetry(service_name: str = "agentic_rag"):
    """Best-effort initialize OpenTelemetry tracing and instrumentations.

    This function lazy-imports opentelemetry packages and instruments FastAPI,
    requests, and SQLAlchemy when available. If the required packages are not
    installed, this is a no-op.
    """
    global _OTEL_INITIALIZED
    if _OTEL_INITIALIZED:
        return True
    try:
        from opentelemetry import trace
        from opentelemetry.sdk.resources import Resource
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor
        try:
            from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
        except Exception:
            try:
                from opentelemetry.exporter.otlp.trace_exporter import OTLPSpanExporter
            except Exception:
                OTLPSpanExporter = None

        if OTLPSpanExporter is None:
            return False

        endpoint = None
        # standard env vars: OTEL_EXPORTER_OTLP_ENDPOINT or OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        import os

        endpoint = os.getenv("OTEL_EXPORTER_OTLP_TRACES_ENDPOINT") or os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT")

        resource = Resource.create({"service.name": service_name})
        provider = TracerProvider(resource=resource)
        trace.set_tracer_provider(provider)

        exporter_kwargs = {}
        if endpoint:
            exporter_kwargs["endpoint"] = endpoint
        exporter = OTLPSpanExporter(**exporter_kwargs) if OTLPSpanExporter is not None else None
        if exporter is not None:
            span_processor = BatchSpanProcessor(exporter)
            provider.add_span_processor(span_processor)

        # instrument frameworks where possible
        try:
            from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
            # Application will instrument FastAPI at startup (main.py) by calling this module
            FastAPIInstrumentor.instrument_app = FastAPIInstrumentor.instrument_app  # noqa: E702
        except Exception:
            pass

        try:
            from opentelemetry.instrumentation.requests import RequestsInstrumentor
            RequestsInstrumentor().instrument()
        except Exception:
            pass

        try:
            from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
            SQLAlchemyInstrumentor().instrument()
        except Exception:
            pass

        _OTEL_INITIALIZED = True
        logger.info("OpenTelemetry initialized (endpoint=%s)", endpoint)
        return True
    except Exception as e:
        logger.debug("OpenTelemetry not initialized: %s", e)
        return False
